### ISSUE TITLE
Detect When An OS X User Has Launched Atom From A launchd Launched Process

### ISSUE THREAD

**Issue by joefitzgerald** [atom-community/environment#1]
Includes:

* Finder
* Spotlight
* Dock
* [open](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/open.1.html)

We need to detect this so that we can take action to patch the environment for these users, ideally using their shell's environment.

**Comment by joefitzgerald** [comment]
If `PATH` is equal to "/usr/bin:/bin:/usr/sbin:/sbin" on OS X 10.10, this indicates Atom was launched from a `launchd` launched process.

**Comment by danielbayley** [comment]
> If PATH is equal to /usr/bin:/bin:/usr/sbin:/sbin on OS X 10.10, this indicates Atom was launched from a launchd launched process.

Is that still the case? Only when I did a fresh install recently the default `PATH` was prefixed with `/usr/local/bin:` as `cat /etc/paths` reveals
```
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
```
and that was before any Homebrew installation.

**Comment by joefitzgerald** [comment]
I know this to be true on my machine and @lee-dohm 's machine. Happy to take reports from others, of `process.env.PATH` when launched via the Dock, Finder, Spotlight, or `open`.

**Comment by danielbayley** [comment]
Actually I get `/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin`. Iv'e no idea how/why `/usr/local/bin` gets moved to the end.

I normally have a bunch of stuff in my `~/.bash`[`rc`/`_profile`] that sets the `PATH` which I disabled to test this.

What's the exact goal of this package?

Also looks very similar to [env-from-shell](https://atom.io/packages/env-from-shell).
