### ISSUE TITLE
Why is this a service and not an `npm` package?

### ISSUE THREAD

**Issue by jordwalke** [atom-community/environment#15]
Could this be an `npm` module? I think people would like to be able to develop packages, and _know_ they have a sane/reliable environment on Atom 1.6 and 1.7 regardless of if the user had also installed this plugin. It would be nice to not require that users also install `environment` in order to get this to work correctly.

**Comment by joefitzgerald** [comment]
This package is deprecated; you should uninstall it. See https://github.com/atom/atom/pull/12562 for more information.
