### ISSUE TITLE
Not working with fish

### ISSUE THREAD

**Issue by aliksend** [atom-community/environment#21]
Hello

I'm using latest version of Atom (1.7.3) with all updates on OS X 10.11.4 with [fish](https://fishshell.com/) as default shell. 

When I opens terminal and launching `env` I can see various defined variables including `GOPATH`. 
But when I'm launching Atom the [autocomplete-go](https://atom.io/packages/autocomplete-go) package (that requires `environment` package as dependence) tells me that it can't found `gocode` tool that already installed. 

I can confirm that problem not in `autocomplete-go` but  in this package because when I opens DevTools and printing `process.env.GOPATH` I see `undefined`, but after launching [env-from-shell](https://atom.io/packages/env-from-shell) the `process.env.GOPATH` becomes defined and `autocomplete-go` working correct.

BTW, `env-from-shell` had the same problem, and they have a [solution](https://github.com/aki77/atom-env-from-shell/issues/1). Can you apply something like that?

Thanks

**Comment by joefitzgerald** [comment]
This package is deprecated; you should uninstall it. See https://github.com/atom/atom/pull/12562 for more information.
